### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by abeaumont** [pyroscope-io/pyroscope-java#19]
Trying to build the java agent with `openjdk:17-slim-bullseye` docker image yields the following error:

```
> startup failed:
   General error during conversion: Unsupported class file major version 61
```

**Comment by tokuhirom** [comment]
When run `./gradlew build`, I got this error:

```
ExponentialBackoffTest > test() FAILED
    org.mockito.exceptions.base.MockitoException: 
    Mockito cannot mock this class: class java.util.Random.

    Mockito can only mock non-private & non-final classes.
    If you're not sure why you're getting this error, please report to the mailing list.


    Java               : 17
    JVM vendor name    : Eclipse Adoptium
    JVM vendor version : 17.0.2+8
    JVM name           : OpenJDK 64-Bit Server VM
    JVM version        : 17.0.2+8
    JVM info           : mixed mode
    OS name            : Mac OS X
    OS version         : 12.3


    Underlying exception : java.lang.IllegalStateException: Cannot access annotation property public abstract java.lang.String jdk.internal.util.random.RandomSupport$RandomGeneratorProperties.name()
        at io.pyroscope.javaagent.ExponentialBackoffTest.test(ExponentialBackoffTest.java:18)

        Caused by:
        java.lang.IllegalStateException: Cannot access annotation property public abstract java.lang.String jdk.internal.util.random.RandomSupport$RandomGeneratorProperties.name()
            at net.bytebuddy.description.annotation.AnnotationDescription$ForLoadedAnnotation.getValue(AnnotationDescription.java:666)
            at net.bytebuddy.implementation.attribute.AnnotationAppender$Default.handle(AnnotationAppender.java:298)
            at net.bytebuddy.implementation.attribute.AnnotationAppender$Default.doAppend(AnnotationAppender.java:361)
            at net.bytebuddy.implementation.attribute.AnnotationAppender$Default.append(AnnotationAppender.java:338)
            at net.bytebuddy.implementation.attribute.TypeAttributeAppender$ForInstrumentedType.apply(TypeAttributeAppender.java:93)
            at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5743)
            at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:232)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659)
            at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:207)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:47)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:77)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:43)
            at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:43)
            at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:53)
            at org.mockito.internal.MockitoCore.mock(MockitoCore.java:84)
            at org.mockito.Mockito.mock(Mockito.java:1954)
            at org.mockito.Mockito.mock(Mockito.java:1865)
            ... 1 more

            Caused by:
            java.lang.IllegalAccessException: class net.bytebuddy.description.annotation.AnnotationDescription$ForLoadedAnnotation cannot access interface jdk.internal.util.random.RandomSupport$RandomGeneratorProperties (in module java.base) because module java.base does not export jdk.internal.util.random to unnamed module @951fdc1
                at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
                at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
                at java.base/java.lang.reflect.Method.invoke(Method.java:560)
                at net.bytebuddy.description.annotation.AnnotationDescription$ForLoadedAnnotation.getValue(AnnotationDescription.java:645)
                ... 24 more

10 tests completed, 1 failed
```

**Comment by abeaumont** [comment]
Thanks, @tokuhirom for your contributions! Now it works fine on Java 17.
